### ISSUE TITLE
Google Authentication Error

### ISSUE THREAD

**Issue by leomc1118** [Tvcz/AutoCalendarForNEUBanner#1]
New error blocks export. 

"Access blocked: Auto Calendar for NEU Banner’s request is invalid

You can’t sign in because Auto Calendar for NEU Banner sent an invalid request."

"Custom URI scheme is not supported on Chrome apps.
Request details: flowName=GeneralOAuthFlow"

**Comment by leomc1118** [comment]
https://stackoverflow.com/questions/77351341/error-400-invalid-request-custom-uri-scheme-is-not-supported-on-chrome-apps

**Comment by leomc1118** [comment]
realized this issue only occurs on Arc browser

**Comment by Tvcz** [comment]
Oh wow never expected anyone to actually open an issue here haha. I will look into it when I have the chance.
